openapi: 3.0.0
info:
  title: ScholarFlow Matchmaking API
  version: 1.0.0
paths:
  /api/v1/matchmaking/analyze:
    post:
      summary: Analyze manuscript and recommend reviewers
      description: |
        Generates a vector for the provided manuscript data and queries the database
        for reviewers with high cosine similarity.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                manuscript_id:
                  type: string
                  format: uuid
                  description: Optional ID if manuscript exists
                title:
                  type: string
                abstract:
                  type: string
                  description: Optional; when empty, fall back to title-only analysis
      responses:
        '200':
          description: List of recommended reviewers
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      recommendations:
                        type: array
                        items:
                          $ref: '#/components/schemas/ReviewerRecommendation'
                      insufficient_data:
                        type: boolean
                        description: True when reviewer embedding corpus is below minimum threshold
                      message:
                        type: string

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ReviewerRecommendation:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
        match_score:
          type: number
          format: float
          description: Cosine similarity score (0.0 to 1.0)
        reasons:
          type: array
          items:
            type: string
          description: Matched keywords (optional/future)
