openapi: 3.0.0
info:
  title: User Profile API
  version: 1.0.0
paths:
  /api/v1/user/profile:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
    put:
      summary: Update user profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileUpdate'
      responses:
        '200':
          description: Updated profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'

  /api/v1/user/security/password:
    put:
      summary: Change password
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordUpdate'
      responses:
        '200':
          description: Password updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

components:
  schemas:
    UserProfileUpdate:
      type: object
      properties:
        full_name:
          type: string
          minLength: 1
        title:
          type: string
        affiliation:
          type: string
        orcid_id:
          type: string
          pattern: '^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$'
        google_scholar_url:
          type: string
          format: uri
        avatar_url:
          type: string
          format: uri
        research_interests:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 10
      required:
        - full_name

    UserProfileResponse:
      allOf:
        - $ref: '#/components/schemas/UserProfileUpdate'
        - type: object
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email
            roles:
              type: array
              items:
                type: string

    PasswordUpdate:
      type: object
      properties:
        password:
          type: string
          minLength: 8
        confirm_password:
          type: string
      required:
        - password
        - confirm_password
