openapi: 3.0.3
info:
  title: DOI Registration API
  description: DOI 注册与管理 API
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /doi/register:
    post:
      summary: 触发 DOI 注册
      description: 为已发表文章创建 DOI 注册任务
      operationId: registerDOI
      tags:
        - DOI
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DOIRegisterRequest'
      responses:
        '201':
          description: 注册任务已创建
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DOIRegistration'
        '400':
          description: 请求无效（文章未发表或元数据不完整）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 未授权
        '409':
          description: DOI 已存在

  /doi/{article_id}:
    get:
      summary: 查询 DOI 注册状态
      operationId: getDOIStatus
      tags:
        - DOI
      security:
        - bearerAuth: []
      parameters:
        - name: article_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 注册状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DOIRegistration'
        '404':
          description: 未找到注册记录

  /doi/{article_id}/retry:
    post:
      summary: 手动重试 DOI 注册
      operationId: retryDOI
      tags:
        - DOI
      security:
        - bearerAuth: []
      parameters:
        - name: article_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 重试任务已创建
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DOITask'
        '400':
          description: 状态不允许重试
        '404':
          description: 未找到注册记录

  /doi/tasks:
    get:
      summary: 获取 DOI 任务列表
      operationId: listDOITasks
      tags:
        - DOI Tasks
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, processing, completed, failed]
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: 任务列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DOITaskList'

  /doi/tasks/failed:
    get:
      summary: 获取失败任务列表
      operationId: listFailedDOITasks
      tags:
        - DOI Tasks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 失败任务列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DOITaskList'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    DOIRegisterRequest:
      type: object
      required:
        - article_id
      properties:
        article_id:
          type: string
          format: uuid
          description: 文章 ID

    DOIRegistration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        article_id:
          type: string
          format: uuid
        doi:
          type: string
          example: "10.12345/sf.2026.00001"
          nullable: true
        status:
          type: string
          enum: [pending, submitting, registered, failed]
        attempts:
          type: integer
        error_message:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        registered_at:
          type: string
          format: date-time
          nullable: true

    DOITask:
      type: object
      properties:
        id:
          type: string
          format: uuid
        registration_id:
          type: string
          format: uuid
        task_type:
          type: string
          enum: [register, update]
        status:
          type: string
          enum: [pending, processing, completed, failed]
        attempts:
          type: integer
        max_attempts:
          type: integer
        run_at:
          type: string
          format: date-time
        last_error:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time

    DOITaskList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/DOITask'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    Error:
      type: object
      properties:
        detail:
          type: string
        code:
          type: string
