sequenceDiagram
    participant AE as AE
    participant Lib as Library
    participant Sys as System
    participant Mail as Mail
    participant Rev as Reviewer

    AE->>Lib: 搜索/选择 reviewer
    alt 库内不存在
      AE->>Lib: 新增 reviewer
    end

    AE->>Sys: 发起邀请
    Sys->>Sys: 生成 token
    Sys->>Mail: 发送邀请邮件
    Mail-->>Rev: 收到邀请

    Rev->>Sys: 打开 magic link
    alt 接受
      Sys->>Rev: 打开审稿工作台
      Rev->>Sys: 提交审稿意见
      Sys-->>AE: 通知已完成
    else 拒绝
      Rev->>Sys: 提交拒绝原因
      Sys-->>AE: 通知需重邀
    end
